### ISSUE TITLE
Motor library not working with Timer1

### ISSUE THREAD

**Issue by kjgregory** [adafruit/Adafruit_Motor_Shield_V2_Library#13]
Immediately after running AFMS.begin(), I'm running a setup routine that sets up Timer1 as a capture/compare timer to be used for generating 1Hz timed interrupts. It is at this time that my Arduino seems to get stuck. This timer and the rest of my code ran just fine before I added the code to run the motor shield and it also works fine if I comment out the timer initialization. 

It doesn't appear that the motor shield library is using timer1, but maybe it is. I can't think of any other reason why this wouldn't work. Anyway, here is my timer initialization routine:

```C++
  cli();//stop interrupts

  //set timer1 interrupt at 1Hz
  TCCR1A = 0;// set entire TCCR1A register to 0
  TCCR1B = 0;// same for TCCR1B
  TCNT1  = 0;//initialize counter value to 0
  // set compare match register for 1hz increments
  OCR1A = LOG_INTERVAL;// = (16*10^6) / (interval*1024) - 1 (must be <65536) (interval in seconds)
  // turn on CTC mode
  TCCR1B |= (1 << WGM12);
  // Set CS10 and CS12 bits for 1024 prescaler
  TCCR1B |= (1 << CS12) | (1 << CS10);  
  // enable timer compare interrupt
  TIMSK1 |= (1 << OCIE1A);

  sei();//allow interrupts
```

**Comment by ladyada** [comment]
yah - this library doesnt use Timer1 at all, it only uses i2c. it could be something else you're doing that is causing it to hiccup :/ you can try posting to the adafruit forum if you'd like for ideas :)
