### ISSUE TITLE
yield 

### ISSUE THREAD

**Issue by disappear123df** [adafruit/Adafruit_Motor_Shield_V2_Library#26]
i keep getting this when when ever i verify any of the example 

/home/disappear/sketchbook/libraries/AdafruitMotorShieldV2/Adafruit_MotorShield.cpp: In member function ‘void Adafruit_StepperMotor::step(uint16_t, uint8_t, uint8_t)’:
/home/disappear/sketchbook/libraries/AdafruitMotorShieldV2/Adafruit_MotorShield.cpp:237:11: error: ‘yield’ was not declared in this scope
     yield(); // required for ESP8266
           ^

**Comment by ladyada** [comment]
what are you using to compile? what board?

**Comment by disappear123df** [comment]
infiduino R3

**Comment by ladyada** [comment]
?? dunno what that is, please try a genuine arduino or you can remove that line :)

**Comment by disappear123df** [comment]
i remove the line and it work thank you
