### ISSUE TITLE
Getting a error compiling code. Can anyone help? 

### ISSUE THREAD

**Issue by topnotchstang** [adafruit/Adafruit_Motor_Shield_V2_Library#30]
Arduino: 1.8.0 (Mac OS X), Board: "Arduino/Genuino Uno"

cory_upwork:17: error: expected ',' or ';' before 'void'
 void forwardstep()
 ^
cory_upwork:27: error: 'forwardstep' was not declared in this scope
 AccelStepper Astepper(forwardstep,backwardstep);
                       ^
exit status 1
expected ',' or ';' before 'void'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

![18641835_1820797877949781_271338971_o](https://cloud.githubusercontent.com/assets/28833600/26280636/0f32d9b8-3dab-11e7-9341-282a035e079d.png)

**Comment by ladyada** [comment]
you are missing a semicolon on the previous line

please check your code carefully before submitting issues - thanks!
