### ISSUE TITLE
Request, 12 bit resolution for DC motors?

### ISSUE THREAD

**Issue by MiloMindbender** [adafruit/Adafruit_Motor_Shield_V2_Library#33]
I noticed this hardware can do 12 bit resolution for DC motors but that this library doesn't support it.  I made a mod to support it and found it worked much better in my project.

It is very easy to support, you just need to add another function, for example.

```
void Adafruit_DCMotor::setSpeed12bit(uint8_t speed) {
  MC->setPWM(PWMpin, speed);
}
```
This is identical to the existing setSpeed function, but the *16 has been removed.  This change wouldn't effect existing projects that use the existing setSpeed function, both would still work.

You would think the difference between 8 and 12 bits wouldn't be noticeable on a DC motor, but I've measured it and at 12 bits every step does make a measurable change in RPM.

**Comment by caternuson** [comment]
Added with #45. See the new `setSpeedFine()` method.
