### ISSUE TITLE
Add a way to check if a shield is attached at an address

### ISSUE THREAD

**Issue by user-name-is-taken** [adafruit/Adafruit_Motor_Shield_V2_Library#34]
Add a function that checks if a shield is attached at an address.

--------------------------------------------------------------------------------------------------

 The current solution is to add a function to Adafruit_MS_PWMServoDriver.cpp, ....h which returns 0 == WIRE.endTransmission() (after a beginTransmission on an address). This output will then be passed through another function in Adafruit_Motorshield.cpp, ....h. This solution is taken from [the arduino I2CScanner](https://playground.arduino.cc/Main/I2cScanner) tutorial.

**Comment by caternuson** [comment]
Should be fixed with #43. The `begin()` method now returns a conditional.
